services:
  fastapi_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nexus_backend_dev
    ports:
      - "${API_PORT:-8000}:8000"
    command: ["sh", "-c", "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"]
    environment:
      - ENV=${ENV:-development}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db_service:5432/${DB_NAME}
      - OLLAMA_HOST=${OLLAMA_HOST:-http://ollama_service:11434}
      - MODEL_NAME=${MODEL_NAME:-qwen2.5-coder:1.5b}
    volumes:
      - ./src:/app/src
      - ./templates:/app/templates
    depends_on:
      db_service:
        condition: service_healthy
    networks:
      - nexus-network

  db_service:
    image: postgres:16-alpine
    container_name: nexus_postgres_dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "127.0.0.1:${DB_PORT:-5432}:5432"
    volumes:
      - nexus_db_dev_data:/var/lib/postgresql/data
    networks:
      - nexus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5

  ollama_service:
    image: ollama/ollama:latest
    container_name: nexus_ollama_dev
    ports:
      - "127.0.0.1:${OLLAMA_PORT:-11434}:11434"
    volumes:
      - nexus_ollama_dev_data:/root/.ollama
    networks:
      - nexus-network
    # Pasamos la variable del modelo al contenedor
    environment:
      - MODEL_NAME=${MODEL_NAME:-qwen2.5-coder:1.5b}
    entrypoint: [ "/bin/sh", "-c" ]
    command: 
      - |
        ollama serve &
        sleep 5
        # Comprobamos si el modelo ya existe localmente en el volumen
        if ollama list | grep -q "$$MODEL_NAME"; then
          echo "✅ El modelo $$MODEL_NAME ya está descargado y listo."
        else
          echo "📥 Descargando el modelo $$MODEL_NAME de forma automática..."
          ollama pull $$MODEL_NAME
        fi
        wait

networks:
  nexus-network:
    name: nexus-network
    driver: bridge

volumes:
  nexus_db_dev_data:
  nexus_ollama_dev_data: